language: node_js
node_js:
  - "8"
before_install:
  - cd ./ember-automation-travis/
install: 
  - npm install
before_script:
  - npm run lint:hbs
  - npm run lint:js
  - npm test
# script:
  # - npm run build
  # - npm run deploy
branches:
  only:
  - master
