language: node_js
node_js:
  - "8"
before_install:
  - cd ./ember-automation-travis/
install: 
  - npm install
  - npm install -g firebase-tools
before_script:
  - npm run lint:hbs
  - npm run lint:js
  - npm test
  - if [ $TRAVIS_BRANCH == "develop" ]; then firebase use dev; fi
  - if [ $TRAVIS_BRANCH == "master" ]; then firebase use prod; fi
script:
  - npm run build
  - npm run deploy
branches:
  only:
  - master
  - develop
  